# Generated by Django 5.0.7 on 2024-07-30 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="TipoPropiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TipoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=50)),
                ("numero", models.IntegerField(blank=True, null=True)),
                ("dpto", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web_app.comuna"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=9, unique=True)),
                ("telefono", models.CharField(max_length=9)),
                (
                    "direccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_app.direccion",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_app.tipousuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=50)),
                ("m2_construidos", models.FloatField()),
                ("m2_totales", models.FloatField()),
                ("estacionamientos", models.SmallIntegerField()),
                ("habitaciones", models.SmallIntegerField()),
                ("banos", models.SmallIntegerField()),
                ("precio_arriendo", models.IntegerField()),
                ("meses_garantia", models.SmallIntegerField()),
                ("disponible", models.BooleanField(null=True)),
                ("fecha_publicacion", models.DateField(auto_now_add=True)),
                ("fecha_modificacion", models.DateField(auto_now=True)),
                ("google_map", models.URLField()),
                (
                    "arrendador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.profile",
                    ),
                ),
                (
                    "direccion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.direccion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comuna",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web_app.region"
            ),
        ),
        migrations.CreateModel(
            name="SolicitudArriendo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_solicitud", models.DateField(auto_now_add=True)),
                ("fecha_revision", models.DateField(null=True)),
                (
                    "arrendatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.profile",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.estado",
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.propiedad",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="propiedad",
            name="interesados",
            field=models.ManyToManyField(
                related_name="propiedades",
                through="web_app.SolicitudArriendo",
                to="web_app.profile",
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="tipo_propiedad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="web_app.tipopropiedad"
            ),
        ),
    ]
