# Generated by Django 5.0.7 on 2024-07-31 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propiedad",
            name="disponible",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to=None)),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.propiedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen",
                "verbose_name_plural": "Imagenes",
            },
        ),
    ]
