# Generated by Django 5.0.7 on 2024-08-02 03:55

import web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0002_alter_propiedad_disponible_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagen",
            name="foto",
            field=models.ImageField(upload_to=web_app.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="descripcion",
            field=models.CharField(max_length=500),
        ),
    ]
